services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: